---
# tasks file for stunnel-role

- name: sanity check that we use at least one of certificate or psk
  fail:
    msg: You should activate at least one of stunnel_use_certificate and stunnel_use_psk
  when: not (stunnel_use_certificate or stunnel_use_psk)

- name: Install SSL backend
  package:
    name: openssl
    update_cache: yes
  register: install_ssl_backend

- name: Install package
  package:
    name: stunnel4 
    force: yes
  register: install_stunnel_4

- include: certificate.yml
  when: stunnel_use_certificate

- include: psk.yml
  when: stunnel_use_psk

- name: Stunnel configuration
  template:
    src: stunnel.conf.j2
    dest: /etc/stunnel/stunnel.conf
  register: stunnel_configuration

- name: Enable stunnel
  lineinfile:
    dest: /etc/default/stunnel4
    state: present
    regexp: ENABLED=
    line: ENABLED=1
  register: enable_stunnel

- name: Start stunnel service
  service:
    name: stunnel4
    state: restarted
    enabled: true
  when: >
    install_stunnel_4.changed or
    enable_stunnel.changed or
    stunnel_configuration.changed or
    (stunnel_psk_file.changed|default(false))
